app:
  name: Approvals
  scheme: https
  host: apps.biola.edu
  relative_url_root: /approvals
  full_url: http://apps.biola.edu/approvals

redis:
  url: "redis://redis1.prod.biola.edu:6379/0"

roz:
  api_base_url: 'https://api.biola.edu/assets/'
  files_base_url: 'https://assets.biola.edu/'
